name: riverpod_analyzer_utils
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  analyzer: ^4.0.0
  collection: ^1.16.0
  meta: ^1.7.0
  path: ^1.8.0
  source_span: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
